### ISSUE TITLE
Debian 11 (bullseye/oldstable) support

### ISSUE THREAD

**Issue by N0rbert** [zabbly/linux#1] opened 2023-08-25 15:49 UTC
Please provide Zabbly repository for Debian 11 (bullseye/oldstable) as it is still widely used.

**Comment by stgraber** [comment] 2023-08-25 16:41
I did initially try adding it, but there was complication with the build.
I'll have to give it another go to see what was going on exactly but I don't remember it being easily solvable.

**Comment by N0rbert** [comment] 2023-08-25 18:24
Theoretically you can get some clues from *bullseye-backports*, as it ships 6.1 - see https://packages.debian.org/bullseye-backports/linux-image-amd64 .

**Comment by stgraber** [comment] 2023-08-25 19:20
Yeah, the issue isn't actually with Debian so much as a firmware (EDK2) issue when running Debian 11 VMs on the arm64 servers I'm using for those builds...

I'm testing a simple workaround for now, only building Debian 11 for x86_64 and not doing Arm at this stage, that should still help the very vast majority of users.

**Comment by stgraber** [comment] 2023-08-25 20:24
Got Debian 11 amd64 building now, should be available in a few hours.

**Comment by stgraber** [comment] 2023-08-26 03:03
It's available now, closing.

**Closed by stgraber** 2023-08-26 03:03 UTC
